volumes:
    comfyuix:

services:
  comfyuix_server:
    build: ./server
    ports:
      - "8888:8888"
    env_file: .env
    volumes:
      - comfyuix:/app/data
    restart: unless-stopped

  comfyuix:
    build: ./client
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      - comfyuix_server
    restart: unless-stopped

  tunnel:
    build: ./comfyuix-tunnel
    env_file: .env
    restart: unless-stopped
