volumes:
    comfyuix:

networks:
  dokploy-network:
    external: true

services:
  # Port 8888
  comfyuix_server:
    build: ./server
    networks:
      - dokploy-network
    env_file: .env
    volumes:
      - comfyuix:/app/data
    restart: unless-stopped

  # Port 80
  comfyuix:
    build: ./client
    networks:
      - dokploy-network
    env_file: .env
    depends_on:
      - comfyuix_server
    restart: unless-stopped

  tunnel:
    build: ./comfyuix-tunnel
    env_file: .env
    restart: unless-stopped
